// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsPortal.Core.ApplicationDbContext;

#nullable disable

namespace NewsPortal.Core.Migrations
{
    [DbContext(typeof(NewsPortalDbContext))]
    partial class NewsPortalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewsPortal.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Health"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Environments"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Politics"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Weather"
                        });
                });

            modelBuilder.Entity("NewsPortal.Core.Models.NewsArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("NewsArticles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            CreatedDateTime = new DateTime(2023, 4, 23, 22, 10, 3, 777, DateTimeKind.Local).AddTicks(3087),
                            Description = "The COVID-19 vaccine rollout has now been expanded to include teens aged 16 and 17, with many states and cities beginning to offer appointments.",
                            Title = "COVID-19 vaccine rollout expands to teens",
                            UpdatedDateTime = new DateTime(2023, 4, 23, 22, 10, 3, 777, DateTimeKind.Local).AddTicks(3104)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 6,
                            CreatedDateTime = new DateTime(2023, 4, 23, 22, 10, 3, 777, DateTimeKind.Local).AddTicks(3124),
                            Description = "Parts of the western United States are experiencing a record-breaking heatwave, with temperatures reaching over 100 degrees Fahrenheit in many areas.",
                            Title = "Record-breaking heatwave hits western United States",
                            UpdatedDateTime = new DateTime(2023, 4, 23, 22, 10, 3, 777, DateTimeKind.Local).AddTicks(3125)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedDateTime = new DateTime(2023, 4, 23, 22, 10, 3, 777, DateTimeKind.Local).AddTicks(3141),
                            Description = "A new study has found that practicing meditation regularly can have significant positive effects on mental health, including reducing symptoms of anxiety and depression.",
                            Title = "New study shows benefits of meditation on mental health",
                            UpdatedDateTime = new DateTime(2023, 4, 23, 22, 10, 3, 777, DateTimeKind.Local).AddTicks(3142)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CreatedDateTime = new DateTime(2023, 4, 23, 22, 10, 3, 777, DateTimeKind.Local).AddTicks(3157),
                            Description = "The government has announced a new round of funding for renewable energy projects, with a focus on solar and wind power.",
                            Title = "Government announces new funding for renewable energy projects",
                            UpdatedDateTime = new DateTime(2023, 4, 23, 22, 10, 3, 777, DateTimeKind.Local).AddTicks(3158)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            CreatedDateTime = new DateTime(2023, 4, 23, 22, 10, 3, 777, DateTimeKind.Local).AddTicks(3172),
                            Description = "A new report has highlighted the growing impact of climate change on the global food supply, with experts warning of potential shortages and price increases.",
                            Title = "New report highlights effects of climate change on global food supply",
                            UpdatedDateTime = new DateTime(2023, 4, 23, 22, 10, 3, 777, DateTimeKind.Local).AddTicks(3173)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedDateTime = new DateTime(2023, 4, 23, 22, 10, 3, 777, DateTimeKind.Local).AddTicks(3188),
                            Description = "A new study has found a significant link between exposure to air pollution and an increased risk of cardiovascular disease, including heart attacks and strokes.",
                            Title = "New study finds link between air pollution and cardiovascular disease",
                            UpdatedDateTime = new DateTime(2023, 4, 23, 22, 10, 3, 777, DateTimeKind.Local).AddTicks(3189)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2023, 4, 23, 22, 10, 3, 777, DateTimeKind.Local).AddTicks(3204),
                            Description = "A technology company has unveiled a new smartphone with advanced features, including a foldable screen and 5G connectivity.",
                            Title = "Technology company unveils new smartphone with advanced features",
                            UpdatedDateTime = new DateTime(2023, 4, 23, 22, 10, 3, 777, DateTimeKind.Local).AddTicks(3205)
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            CreatedDateTime = new DateTime(2023, 4, 23, 22, 10, 3, 777, DateTimeKind.Local).AddTicks(3220),
                            Description = "An athlete has broken the world record in a track and field event, setting a new standard for performance in the sport.",
                            Title = "Athlete breaks world record in track and field event",
                            UpdatedDateTime = new DateTime(2023, 4, 23, 22, 10, 3, 777, DateTimeKind.Local).AddTicks(3220)
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2023, 4, 23, 22, 10, 3, 777, DateTimeKind.Local).AddTicks(3236),
                            Description = "SpaceX launched a Falcon 9 rocket carrying 60 Starlink internet satellites into orbit from Florida's Cape Canaveral Space Force Station on Monday.",
                            Title = "SpaceX successfully launches Falcon 9 rocket",
                            UpdatedDateTime = new DateTime(2023, 4, 23, 22, 10, 3, 777, DateTimeKind.Local).AddTicks(3236)
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            CreatedDateTime = new DateTime(2023, 4, 23, 22, 10, 3, 777, DateTimeKind.Local).AddTicks(3252),
                            Description = "Protests demanding action on climate change have erupted in major cities around the world, with thousands of people taking to the streets.",
                            Title = "Climate change protests erupt in major cities around the world",
                            UpdatedDateTime = new DateTime(2023, 4, 23, 22, 10, 3, 777, DateTimeKind.Local).AddTicks(3253)
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            CreatedDateTime = new DateTime(2023, 4, 23, 22, 10, 3, 777, DateTimeKind.Local).AddTicks(3268),
                            Description = "Apple has announced a new iPhone model that features a foldable screen, allowing users to have a larger display when needed.",
                            Title = "Apple announces new iPhone with foldable screen",
                            UpdatedDateTime = new DateTime(2023, 4, 23, 22, 10, 3, 777, DateTimeKind.Local).AddTicks(3268)
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            CreatedDateTime = new DateTime(2023, 4, 23, 22, 10, 3, 777, DateTimeKind.Local).AddTicks(3284),
                            Description = "The United Nations has condemned Myanmar's military for human rights violations against the Rohingya minority, including rape, torture, and murder.",
                            Title = "UN condemns Myanmar's military for human rights violations",
                            UpdatedDateTime = new DateTime(2023, 4, 23, 22, 10, 3, 777, DateTimeKind.Local).AddTicks(3285)
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            CreatedDateTime = new DateTime(2023, 4, 23, 22, 10, 3, 777, DateTimeKind.Local).AddTicks(3300),
                            Description = "Protests demanding action on climate change have erupted in major cities around the world, with thousands of people taking to the streets.",
                            Title = "Climate change protests erupt in major cities around the world",
                            UpdatedDateTime = new DateTime(2023, 4, 23, 22, 10, 3, 777, DateTimeKind.Local).AddTicks(3301)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
